#!/bin/sh
set -e

[ -f /local/msmtprc ] && cp /local/msmtprc /etc/msmtprc && chmod 644 /etc/msmtprc

chown -R www-data app/uploads
[ -d app/cache ] ||  mkdir app/cache
chown -R www-data app/cache

umask 0027

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"
