---
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    restart: always
    depends_on:
      - fpm
    ports:
      - "127.0.0.1:8080:8080"
    env_file: .env
    environment:
      NOMAD_ADDR_fastcgi: "fpm:9000"
      APP_DOMAIN: "localhost"
    volumes:
      - ./:/srv/wordpress/:ro
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: fpm
    volumes:
      - ./:/srv/wordpress/
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
        restart: true
  database:
    image: mariadb:10.11.11
    ports:
      - "127.0.0.1:3306:3306"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -p$$MYSQL_ROOT_PASSWORD ping || exit 2"]
      interval: 10s      # check every 10 seconds
      timeout: 5s        # fail if no response within 5 seconds
      retries: 5         # mark as unhealthy after 5 failures
      start_period: 2s  # give MariaDB time to start before healthchecks begin
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "127.0.0.1:8081:80"
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
        restart: true

volumes:
  db_data:
