name: Debug Jenkins Trigger

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to send to Jenkins"
        required: false

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Trigger Jenkins job
        env:
          JENKINS_URL: ${{ vars.JENKINS_URL }}
          JENKINS_JOB: ${{ vars.JENKINS_JOB }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
          GITHUB_SHA: ${{ github.sha }}
          INPUT_COMMIT_SHA: ${{ inputs.commit_sha }}
        run: |
          COMMIT_SHA=${INPUT_COMMIT_SHA:-$GITHUB_SHA}
          echo "Using COMMIT_SHA=$COMMIT_SHA"
          curl --fail --silent --show-error --request POST --header "Content-Type: application/x-www-form-urlencoded" \
            --user "github:${JENKINS_PASSWORD}" \
            --data-urlencode "token=${JENKINS_TOKEN}" \
            --data-urlencode "COMMIT_SHA=${COMMIT_SHA}" "${JENKINS_URL}/job/${JENKINS_JOB}/build"
